kind: pipeline
name: default

workspace:
  base: /go
  path: src/test_ci

steps:
- name: dep
  image: golang
  commands:
  - go get github.com/golang/dep/...
  - dep ensure

- name: backend
  image: golang
  commands:
  - go build
  - go test ./...

- name: build-latest-image
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password: 
      from_secret: DOCKER_PASSWORD
    repo: thecodeisgreen/test_ci
    auto_tag: true

trigger:
  event:
    - push
    - tag