kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/thecodeisgreen/test_ci
clone:
  depth: 50

steps:
- name: dep
  image: golang
  commands:
  - env | grep "GOPATH"
  - go get github.com/golang/dep/...
  - dep ensure

- name: backend
  image: golang
  commands:
  - env | grep "GOPATH"
  - pwd
  - ls -ail
  - go build
  - go test ./...
  environment:
    GOPATH: /go/src/github.com/thecodeisgreen/test_ci

- name: build-image
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password: 
      from_secret: DOCKER_PASSWORD
    repo: thecodeisgreen/test_ci
    tags: latest

trigger:
  branch:
    - master
  event:
    - push