kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/thecodeisgreen/test_ci
  
steps:
- name: dep
  image: golang
  commands:
    - go get github.com/golang/dep/...
    - dep ensure

- name: backend
  image: golang
  commands:
    - go build
    - go test

trigger:
  branch:
    - master
  event:
    - push